name: Dev Validate Test Build Upload

on:
  push:
    branches:
      - development

jobs:

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout the source code
      uses: actions/checkout@master
      
    - name: Validate Config
      run: python3 tools/SQF-validate/config_style_checker.py

    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'src'

  test:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - name: Checkout the code
      uses: actions/checkout@master

    - name: Validate SQF with SQF-VM
      run: |
        cd src
        New-Item .\config\user_local_config.hpp -ItemType File
        cd ..\
        .\tools\SQF-VM\sqfvm.exe -a --no-execute-print --disable-macro-warnings --load . -i D:\a\Vindicta\Vindicta\src\Tests\RunTests.sqf

  build:
    runs-on: windows-latest
    timeout-minutes: 5
    needs: [validate, test]
    steps:
    - name: Checkout the code
      uses: actions/checkout@master

    - name: Build Missions
      run: '.\tools\Builder\buildMissions.ps1 -verPatch ${{ github.run_number }}_DEV'

    - name: Build addons
      run: '.\tools\Builder\buildAddons.ps1 -metaFileName meta_dev.cpp'

    - name: Upload build addon artifact
      uses: actions/upload-artifact@v2
      with:
        name: armaAddon
        path: _build\addon\Vindicta

    - name: Upload separate missions artifact
      uses: actions/upload-artifact@v2
      with:
        name: separateMissions
        path: _build\missions\separatePBO

  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    steps:
    - name: Download addon artifact
      uses: actions/download-artifact@v2
      with:
        name: armaAddon
        path: armaAddon

    - name: Download separate missions artifact
      uses: actions/download-artifact@v2
      with:
        name: separateMissions
        path: separateMissions
