name: Publish to Workshop

on:
  release:
    types:
      - published

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@master

    - name: Validate Config
      run: python3 tools/SQF-validate/config_style_checker.py

    - name: Check for BOM
      uses: arma-actions/bom-check@master
      with:
        path: 'Vindicta.Altis'

  test:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
    - name: Checkout the code
      uses: actions/checkout@master

    - name: Validate SQF with SQF-VM
      run: |
        cd src
        New-Item .\config\user_local_config.hpp -ItemType File
        ..\tools\SQF-VM\sqfvm.exe -a --no-execute-print --disable-macro-warnings --load . -i D:\a\Vindicta\Vindicta\src\Tests\RunTests.sqf

  build:
    runs-on: windows-latest
    timeout-minutes: 5
    needs: [validate, test]
    steps:
    - uses: actions/checkout@master

    - name: Get Release Info
      run: |
        $latest_release = (Invoke-WebRequest https://api.github.com/repos/${{ github.repository }}/releases | ConvertFrom-Json).Get(0)
        $versionSplit = $latest_release.tag_name.replace('v','').split('.')
        $major = $versionSplit[0]
        $minor = $versionSplit[1]
        Set-Content -Path .\configs\majorVersion.hpp -Value $major -Force -NoNewline
        Set-Content -Path .\configs\minorVersion.hpp -Value $minor -Force -NoNewline
        $uploadurl = $latest_release.upload_url
        $changelog = $latest_release.body
        Set-Content -Path .\_uploadurl -Value $uploadurl -Force -NoNewline
        Set-Content -Path .\_changelog -Value $changelog -Force -NoNewline

    - name: Build Missions
      run: '.\tools\Builder\buildMissions.ps1 -verPatch ${{ github.run_number }}'

    - name: Build addons
      run: '.\tools\Builder\buildAddons.ps1 -metaFileName meta_main.cpp'
        
    - uses: actions/upload-artifact@v1
      with:
        name: armaAddon
        path: _build\addon\Vindicta

    - uses: actions/upload-artifact@v1
      with:
        name: armaMissions
        path: _build\missions\separatePBO
          
    - uses: actions/upload-artifact@v1
      with:
        name: _uploadurl
        path: _uploadurl
          
    - uses: actions/upload-artifact@v1
      with:
        name: _changelog
        path: _changelog

  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [build]
    steps:
    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: armaAddon

    - name: Download missions build
      uses: actions/download-artifact@v1
      with:
        name: armaMissions

    - uses: actions/download-artifact@v1
      with:
        name: _uploadurl
        path: .
        
    - uses: actions/download-artifact@v1
      with:
        name: _changelog
        path: .

    - id: release_info
      run: |
        ls
        echo "::set-output name=upload_url::$(cat _uploadurl)"
        changelog=`cat _changelog`
        echo $changelog
        changelog="${changelog//'%'/'%25'}"
        changelog="${changelog//$'\n'/'%0A'}"
        changelog="${changelog//$'\r'/'%0D'}" 
        echo "::set-output name=changelog::$changelog"

    - name: Prepare for Release
      run: |
        mv armaAddon @Vindicta
        zip -r vindicta.zip @Vindicta
        zip -r missions.zip armaMissions
        ls

    - name: Publish addon to GitHub Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_info.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: vindicta.zip
        asset_name: vindicta.zip
        asset_content_type: application/zip

    - name: Publish missions to GitHub Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release_info.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: missions.zip
        asset_name: missions.zip
        asset_content_type: application/zip
